[workspace]
members = ["sb", "sdisk", "cli"]
resolver = "2"

[workspace.package]
authors = ["David Irvine <david.irvine@maidsafe.net>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/dirvine/saorsa-cli"
homepage = "https://github.com/dirvine/saorsa-cli"

[workspace.dependencies]
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.42", features = ["full"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
openssl = { version = "0.10", features = ["vendored"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
openssl = { version = "0.10", features = ["vendored"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true