name: Test Release Workflow
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Test Release Creation
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8
        with:
          tag_name: v0.3.13-test
          body: |
            ## Test Release v0.3.13-test

            This is a test release to verify GH_RELEASE_TOKEN works.
          draft: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}