name: Test Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Test Release Creation
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8
        with:
          tag_name: ${{ github.ref_name }}
          body: |
            ## Test Release ${{ github.ref_name }}

            This is a test release using GH_RELEASE_TOKEN.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}